### PR TITLE
Fix uninstallation script and fix  broken recovery check + only install to containerd nodes

### LINKED ISSUE #49: Prevent installation on nodes without containerd
Related to other feature #10 

Installation/Daemon agent set should be limited only to nodes with proper labels 

```
worker.gardener.cloud/cri-name=containerd
```

idea based on this example from gvisor: https://github.com/gardener/gardener-extension-runtime-gvisor/blob/master/charts/internal/gvisor-installation/templates/daemonset-containerd.yaml#L12

```yaml
      nodeSelector:
{{ toYaml .Values.config.nodeSelector | indent 8 }}
```

and default values 
```
  nodeSelector:
    worker.gardener.cloud/cri-name: containerd
    worker.gardener.cloud/pool: gvisor-pool
```
from https://github.com/gardener/gardener-extension-runtime-gvisor/blob/master/charts/internal/gvisor-installation/values.yaml#L7

### PR DESCRIPTION
**Pull request by ppalucki**
1. Use the same finalizer for bot controllers (configmap watcher shouldn't block removing extension)
2. Fix checks in installation script so that "activating" state is not nessecrilty broken - we just waiting for failed state
3. require containerd annotation resolves #49 
4. make hacks/script usable for other cluster that "garden-local"

### CODE REVIEW

File: hacks/generate-controller-registration.sh [hunk 1]
```diff
@@ -38,15 +38,15 @@ providerConfig:
     ### "image" overwrites extension (for seed) and "images" overwrite installation/agent (for shoot) images defined in charts/images.yaml
     #image:
     #  repository: v2.isvimgreg.com/gardener-extension-cri-resmgr
-    #  tag: mybranch
+    #  tag: latest
```
Comment (mmucek95) [inline hacks/generate-controller-registration.sh:41]: Is it compatible with what is written in the documentation? Maybe it would be more helpful to leave it as it was with "mybranch"

File: hacks/generate-controller-registration.sh [hunk 2]
```diff
@@ -113,7 +103,8 @@ spec:
   - kind: Extension
     type: cri-resmgr-extension
     globallyEnabled: false
-    reconcileTimeout: "60s"
+    # we need to wait for kubelet readines and almost whole shoot ready - give it a pleanty of time 5 minutes
```
Comment (mmucek95) [inline hacks/generate-controller-registration.sh:106]: s/readines/readiness

File: pkg/controller/lifecycle/add.go [hunk 3]
```diff
@@ -107,7 +107,7 @@ func AddConfigMapWatchingControllerToManager(mgr manager.Manager, options *optio
 	configReconcilerArgs := extension.AddArgs{
 		Actuator:        NewActuator(consts.ActuatorName + consts.ConfigsSuffix),
 		Resync:          60 * time.Minute,
-		FinalizerSuffix: consts.ExtensionType + consts.ConfigsSuffix,
+		FinalizerSuffix: consts.ExtensionType, // on purpuse we're using the same finalizer as original controller to "delete" only once without need for waiting for another "configs" controller
```
Comment (mmucek95) [inline pkg/controller/lifecycle/add.go:110]: Sound a bit odd to me. I would propose something like that:
we're using the same finalizer as the original controller on purpose to "delete" only once without a need to wait for another "configs" controller

**Review by mmucek95 — CHANGES_REQUESTED** [review]

File: charts/internal/cri-resmgr-installation/templates/installaton-configmap.yaml [hunk 4]
```diff
@@ -148,41 +149,99 @@ data:
...
     # Install cri-rm
     install
 
     #echo "Setup termination handler."
-    trap uninstall SIGTERM SIGINT
+    trap uninstall_and_quit SIGTERM SIGINT
 
     # Sleep after installation the task
     echo "cri-resource-manager installed. Run checks in a loop..."
+    # Just five seconds  before first check to allow kubelet/cri to go from activating to active state
```
[the remark this answers is not in the document]
Comment (ppalucki) [reply charts/internal/cri-resmgr-installation/templates/installaton-configmap.yaml:176]: fixed.

File: charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml [hunk 5]
```diff
@@ -31,8 +31,11 @@ spec:
     spec:
       hostPID: true
       hostIPC: true
-      # give a minute to uninstall cri-rm
-      terminationGracePeriodSeconds: 60
+      # give a 30 seconds to uninstall cri-rm
```
[the remark this answers is not in the document]
Comment (ppalucki) [reply charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml:34]: fixed

File: hacks/generate-controller-registration.sh (hunk 2 above)
Comment (ppalucki) [reply hacks/generate-controller-registration.sh:106]: fixed

File: pkg/controller/lifecycle/add.go (hunk 3 above)
Comment (ppalucki) [reply pkg/controller/lifecycle/add.go:110]: yes that sounds much better.

**Review by mmucek95 — APPROVED** [review]
